# fly.toml app configuration file generated for vorobei on 2023-11-27T14:41:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vorobei"
primary_region = "waw"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
